syms Re Rbi Rs Rp Cd Cg V1 Vo Vbi w V I a b c d e V_set I_set;
a=1/(1+exp(-Vbi+V_set));
b=1/(1+exp(Vbi-V_set));
c=1/(1+exp(V_set-Vo));
d=b*c;
e=1/(1+exp(Vo-V_set));
V1=V_set-I_set*Re;
%f_xt=fourier(Re);
%f_ht=fourier(a);
%result = ifourier(f_xt * f_ht)
f=Re*a+d*(Rbi*V_set*(V1-Vbi))/((V1-Vbi)^2+(V1*w*Cd*Rbi-Vbi*w*Cd*Rbi+V1*Rbi*w*Cg)^2)+e*V_set*(Rbi*Rs*Rp*Rs*Rp*V1-Rbi*Rs*Rp*Rs*Rp*Vbi+Rbi*Rs*Rp*Rbi*Rp*V1-Rbi*Rs*Rp*Rbi*Rp*Vo+V1*Rbi*Rs)/(V1*Rs*Rp-Vbi*Rs*Rp+V1*Rbi*Rp-Vo*Rbi*Rp+V1*Rbi*Rs)^2;
Re/(exp(V_set - Vbi) + 1) + (Rbi*Rs*V1 + Rbi*Rp^2*Rs^2*V1 + Rbi^2*Rp^2*Rs*V1 - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo)/((exp(Vo - V) + 1)*(Rbi*Rp*V1 + Rbi*Rs*V1 + Rp*Rs*V1 - Rbi*Rp*Vo - Rp*Rs*Vbi)^2) + (Rbi*V*(V1 - Vbi))/(((Cd*Rbi*V1*w + Cg*Rbi*V1*w - Cd*Rbi*Vbi*w)^2 + (V1 - Vbi)^2)*(exp(Vbi - V) + 1)*(exp(V - Vo) + 1));

%Re
I1=diff(f,Re);

%1/(exp(V - Vbi) + 1) - (I*Rbi^2*Rp^2*Rs + I*Rbi*Rp^2*Rs^2 + I*Rbi*Rs)/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^2) + (2*(I*Rbi*Rp + I*Rbi*Rs + I*Rp*Rs)*(Rbi*Rs*(V - I*Re) - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo + Rbi*Rp^2*Rs^2*(V - I*Re) + Rbi^2*Rp^2*Rs*(V - I*Re)))/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^3) - (I*Rbi*V)/((exp(Vbi - V) + 1)*(exp(V - Vo) + 1)*((Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V + I*Re)^2)) + (Rbi*V*(2*I*(Vbi - V + I*Re) - 2*(Cd*I*Rbi*w + Cg*I*Rbi*w)*(Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w))*(Vbi - V + I*Re))/((exp(Vbi - V) + 1)*(exp(V - Vo) + 1)*((Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V + I*Re)^2)^2)
1/(exp(V_set - Vbi) + 1) - (V_set*(I_set*Rbi^2*Rp^2*Rs + I_set*Rbi*Rp^2*Rs^2 + I_set*Rbi*Rs))/((exp(Vo - V_set) + 1)*(Rbi*Rp*(V_set - I_set*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set - I_set*Re) + Rp*Rs*(V_set - I_set*Re))^2) + (2*V_set*(I_set*Rbi*Rp + I_set*Rbi*Rs + I_set*Rp*Rs)*(Rbi*Rs*(V_set - I_set*Re) - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo + Rbi*Rp^2*Rs^2*(V_set - I_set*Re) + Rbi^2*Rp^2*Rs*(V_set - I_set*Re)))/((exp(Vo - V_set) + 1)*(Rbi*Rp*(V_set - I_set*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set - I_set*Re) + Rp*Rs*(V_set - I_set*Re))^3) - (I_set*Rbi*V_set)/((exp(Vbi - V_set) + 1)*(exp(V_set - Vo) + 1)*((Cd*Rbi*w*(V_set - I_set*Re) + Cg*Rbi*w*(V_set - I_set*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V_set + I_set*Re)^2)) + (Rbi*V_set*(2*I_set*(Vbi - V_set + I_set*Re) - 2*(Cd*I_set*Rbi*w + Cg*I_set*Rbi*w)*(Cd*Rbi*w*(V_set - I_set*Re) + Cg*Rbi*w*(V_set - I_set*Re) - Cd*Rbi*Vbi*w))*(Vbi - V_set + I_set*Re))/((exp(Vbi - V_set) + 1)*(exp(V_set - Vo) + 1)*((Cd*Rbi*w*(V_set - I_set*Re) + Cg*Rbi*w*(V_set - I_set*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V_set + I_set*Re)^2)^2)

%Rbi
I2=diff(f,Rbi);

%(Rs*(V - I*Re) - Rp^2*Rs^2*Vbi + Rp^2*Rs^2*(V - I*Re) - 2*Rbi*Rp^2*Rs*Vo + 2*Rbi*Rp^2*Rs*(V - I*Re))/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^2) - (2*(Rp*(V - I*Re) - Rp*Vo + Rs*(V - I*Re))*(Rbi*Rs*(V - I*Re) - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo + Rbi*Rp^2*Rs^2*(V - I*Re) + Rbi^2*Rp^2*Rs*(V - I*Re)))/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^3) - (V*(Vbi - V + I*Re))/((exp(Vbi - V) + 1)*(exp(V - Vo) + 1)*((Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V + I*Re)^2)) + (2*Rbi*V*(Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)*(Cd*w*(V - I*Re) - Cd*Vbi*w + Cg*w*(V - I*Re))*(Vbi - V + I*Re))/((exp(Vbi - V) + 1)*(exp(V - Vo) + 1)*((Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V + I*Re)^2)^2)
(V_set*(Rs*(V_set - I_set*Re) - Rp^2*Rs^2*Vbi + Rp^2*Rs^2*(V_set - I_set*Re) - 2*Rbi*Rp^2*Rs*Vo + 2*Rbi*Rp^2*Rs*(V_set - I_set*Re)))/((exp(Vo - V_set) + 1)*(Rbi*Rp*(V_set - I_set*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set - I_set*Re) + Rp*Rs*(V_set - I_set*Re))^2) - (V_set*(Vbi - V_set + I_set*Re))/((exp(Vbi - V_set) + 1)*(exp(V_set - Vo) + 1)*((Cd*Rbi*w*(V_set - I_set*Re) + Cg*Rbi*w*(V_set - I_set*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V_set + I_set*Re)^2)) - (2*V_set*(Rp*(V_set - I_set*Re) - Rp*Vo + Rs*(V_set - I_set*Re))*(Rbi*Rs*(V_set - I_set*Re) - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo + Rbi*Rp^2*Rs^2*(V_set - I_set*Re) + Rbi^2*Rp^2*Rs*(V_set - I_set*Re)))/((exp(Vo - V_set) + 1)*(Rbi*Rp*(V_set - I_set*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set - I_set*Re) + Rp*Rs*(V_set - I_set*Re))^3) + (2*Rbi*V_set*(Cd*Rbi*w*(V_set - I_set*Re) + Cg*Rbi*w*(V_set - I_set*Re) - Cd*Rbi*Vbi*w)*(Cd*w*(V_set - I_set*Re) - Cd*Vbi*w + Cg*w*(V_set - I_set*Re))*(Vbi - V_set + I_set*Re))/((exp(Vbi - V_set) + 1)*(exp(V_set - Vo) + 1)*((Cd*Rbi*w*(V_set - I_set*Re) + Cg*Rbi*w*(V_set - I_set*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V_set + I_set*Re)^2)^2)
%Rs
I3=diff(f,Rs);

%(Rbi*(V - I*Re) - Rbi^2*Rp^2*Vo + Rbi^2*Rp^2*(V - I*Re) - 2*Rbi*Rp^2*Rs*Vbi + 2*Rbi*Rp^2*Rs*(V - I*Re))/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^2) - (2*(Rbi*(V - I*Re) - Rp*Vbi + Rp*(V - I*Re))*(Rbi*Rs*(V - I*Re) - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo + Rbi*Rp^2*Rs^2*(V - I*Re) + Rbi^2*Rp^2*Rs*(V - I*Re)))/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^3)
(V_set*(Rbi*(V_set - I_set*Re) - Rbi^2*Rp^2*Vo + Rbi^2*Rp^2*(V_set - I_set*Re) - 2*Rbi*Rp^2*Rs*Vbi + 2*Rbi*Rp^2*Rs*(V_set - I_set*Re)))/((exp(Vo - V_set) + 1)*(Rbi*Rp*(V_set - I_set*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set - I_set*Re) + Rp*Rs*(V_set - I_set*Re))^2) - (2*V_set*(Rbi*(V_set - I_set*Re) - Rp*Vbi + Rp*(V_set - I_set*Re))*(Rbi*Rs*(V_set - I_set*Re) - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo + Rbi*Rp^2*Rs^2*(V_set - I_set*Re) + Rbi^2*Rp^2*Rs*(V_set - I_set*Re)))/((exp(Vo - V_set) + 1)*(Rbi*Rp*(V_set - I_set*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set - I_set*Re) + Rp*Rs*(V_set - I_set*Re))^3)
%Rp
I4=diff(f,Rp);

%(2*(Rbi*Vo + Rs*Vbi - Rbi*(V - I*Re) - Rs*(V - I*Re))*(Rbi*Rs*(V - I*Re) - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo + Rbi*Rp^2*Rs^2*(V - I*Re) + Rbi^2*Rp^2*Rs*(V - I*Re)))/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^3) - (2*Rbi*Rp*Rs^2*Vbi + 2*Rbi^2*Rp*Rs*Vo - 2*Rbi*Rp*Rs^2*(V - I*Re) - 2*Rbi^2*Rp*Rs*(V - I*Re))/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^2)
(2*V_set*(Rbi*Vo + Rs*Vbi - Rbi*(V_set - I_set*Re) - Rs*(V_set - I_set*Re))*(Rbi*Rs*(V_set - I_set*Re) - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo + Rbi*Rp^2*Rs^2*(V_set - I_set*Re) + Rbi^2*Rp^2*Rs*(V_set - I_set*Re)))/((exp(Vo - V_set) + 1)*(Rbi*Rp*(V_set - I_set*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set - I_set*Re) + Rp*Rs*(V_set - I_set*Re))^3) - (V_set*(2*Rbi*Rp*Rs^2*Vbi + 2*Rbi^2*Rp*Rs*Vo - 2*Rbi*Rp*Rs^2*(V_set - I_set*Re) - 2*Rbi^2*Rp*Rs*(V_set - I_set*Re)))/((exp(Vo - V_set) + 1)*(Rbi*Rp*(V_set - I_set*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set - I_set*Re) + Rp*Rs*(V_set - I_set*Re))^2)
%Vo
I5=diff(f,Vo);

%(2*Rbi*Rp*(Rbi*Rs*(V - I*Re) - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo + Rbi*Rp^2*Rs^2*(V - I*Re) + Rbi^2*Rp^2*Rs*(V - I*Re)))/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^3) - (Rbi^2*Rp^2*Rs)/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^2) - (exp(Vo - V)*(Rbi*Rs*(V - I*Re) - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo + Rbi*Rp^2*Rs^2*(V - I*Re) + Rbi^2*Rp^2*Rs*(V - I*Re)))/((exp(Vo - V) + 1)^2*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^2) - (Rbi*V*exp(V - Vo)*(Vbi - V + I*Re))/((exp(Vbi - V) + 1)*(exp(V - Vo) + 1)^2*((Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V + I*Re)^2))
(2*Rbi*Rp*V_set*(Rbi*Rs*(V_set - I_set*Re) - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo + Rbi*Rp^2*Rs^2*(V_set - I_set*Re) + Rbi^2*Rp^2*Rs*(V_set - I_set*Re)))/((exp(Vo - V_set) + 1)*(Rbi*Rp*(V_set - I_set*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set - I_set*Re) + Rp*Rs*(V_set - I_set*Re))^3) - (Rbi^2*Rp^2*Rs*V_set)/((exp(Vo - V_set) + 1)*(Rbi*Rp*(V_set - I_set*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set - I_set*Re) + Rp*Rs*(V_set - I_set*Re))^2) - (V_set*exp(Vo - V_set)*(Rbi*Rs*(V_set - I_set*Re) - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo + Rbi*Rp^2*Rs^2*(V_set - I_set*Re) + Rbi^2*Rp^2*Rs*(V_set - I_set*Re)))/((exp(Vo - V_set) + 1)^2*(Rbi*Rp*(V_set - I_set*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set - I_set*Re) + Rp*Rs*(V_set - I_set*Re))^2) - (Rbi*V_set*exp(V_set - Vo)*(Vbi - V_set + I_set*Re))/((exp(Vbi - V_set) + 1)*(exp(V_set - Vo) + 1)^2*((Cd*Rbi*w*(V_set - I_set*Re) + Cg*Rbi*w*(V_set - I_set*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V_set + I_set*Re)^2))
%Vbi
I6=diff(f,Vbi);

%(Re*exp(V - Vbi))/(exp(V - Vbi) + 1)^2 - (Rbi*Rp^2*Rs^2)/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^2) - (Rbi*V)/((exp(Vbi - V) + 1)*(exp(V - Vo) + 1)*((Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V + I*Re)^2)) + (2*Rp*Rs*(Rbi*Rs*(V - I*Re) - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo + Rbi*Rp^2*Rs^2*(V - I*Re) + Rbi^2*Rp^2*Rs*(V - I*Re)))/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^3) - (Rbi*V*(Vbi - V + I*Re)*(2*V - 2*Vbi - 2*I*Re + 2*Cd*Rbi*w*(Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)))/((exp(Vbi - V) + 1)*(exp(V - Vo) + 1)*((Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V + I*Re)^2)^2) + (Rbi*V*exp(Vbi - V)*(Vbi - V + I*Re))/((exp(Vbi - V) + 1)^2*(exp(V - Vo) + 1)*((Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V + I*Re)^2))
(Re*exp(V_set - Vbi))/(exp(V_set - Vbi) + 1)^2 - (Rbi*V_set)/((exp(Vbi - V_set) + 1)*(exp(V_set - Vo) + 1)*((Cd*Rbi*w*(V_set - I_set*Re) + Cg*Rbi*w*(V_set - I_set*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V_set + I_set*Re)^2)) - (Rbi*Rp^2*Rs^2*V_set)/((exp(Vo - V_set) + 1)*(Rbi*Rp*(V_set - I_set*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set - I_set*Re) + Rp*Rs*(V_set - I_set*Re))^2) + (2*Rp*Rs*V_set*(Rbi*Rs*(V_set - I_set*Re) - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo + Rbi*Rp^2*Rs^2*(V_set - I_set*Re) + Rbi^2*Rp^2*Rs*(V_set - I_set*Re)))/((exp(Vo - V_set) + 1)*(Rbi*Rp*(V_set - I_set*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set - I_set*Re) + Rp*Rs*(V_set - I_set*Re))^3) - (Rbi*V_set*(Vbi - V_set + I_set*Re)*(2*V_set - 2*Vbi - 2*I_set*Re + 2*Cd*Rbi*w*(Cd*Rbi*w*(V_set - I_set*Re) + Cg*Rbi*w*(V_set - I_set*Re) - Cd*Rbi*Vbi*w)))/((exp(Vbi - V_set) + 1)*(exp(V_set - Vo) + 1)*((Cd*Rbi*w*(V_set - I_set*Re) + Cg*Rbi*w*(V_set - I_set*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V_set + I_set*Re)^2)^2) + (Rbi*V_set*exp(Vbi - V_set)*(Vbi - V_set + I_set*Re))/((exp(Vbi - V_set) + 1)^2*(exp(V_set - Vo) + 1)*((Cd*Rbi*w*(V_set - I_set*Re) + Cg*Rbi*w*(V_set - I_set*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V_set + I_set*Re)^2))

%Cap
h=-a/w*Cg-d*Rbi*V*(w*Cd*Rbi*V1-w*Cd*Rbi*Vbi+V1*Rbi*w*Cg)/((V1-Vbi)^2+(V1*w*Cd*Rbi-Vbi*w*Cd*Rbi+V1*Rbi*w*Cg)^2)-e*Rbi*Rs*Rp*V*(w*Cd*V1-w*Cd*Vbi+V1*w*Cg)*(V1*Rs*Rp-Vbi*Rs*Rp+V1*Rbi*Rp-Vo*Rbi*Rp+V1*Rbi*Rs)^2;
- Cg/(w*(exp(V - Vbi) + 1)) - (Rbi*V*(Cd*Rbi*V1*w + Cg*Rbi*V1*w - Cd*Rbi*Vbi*w))/(((Cd*Rbi*V1*w + Cg*Rbi*V1*w - Cd*Rbi*Vbi*w)^2 + (V1 - Vbi)^2)*(exp(Vbi - V) + 1)*(exp(V - Vo) + 1)) - (Rbi*Rp*Rs*V*(Cd*V1*w + Cg*V1*w - Cd*Vbi*w)*(Rbi*Rp*V1 + Rbi*Rs*V1 + Rp*Rs*V1 - Rbi*Rp*Vo - Rp*Rs*Vbi)^2)/(exp(Vo - V) + 1);

%Cg
I7=diff(h,Cg);
(2*Rbi^2*V*w*(V - I*Re)*(Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2)/((exp(Vbi - V) + 1)*(exp(V - Vo) + 1)*((Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V + I*Re)^2)^2) - (Rbi^2*V*w*(V - I*Re))/((exp(Vbi - V) + 1)*(exp(V - Vo) + 1)*((Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V + I*Re)^2)) - 1/(w*(exp(V - Vbi) + 1)) - (Rbi*Rp*Rs*V*w*(V - I*Re)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^2)/(exp(Vo - V) + 1);

%Cd
I8=diff(h,Cd);
(Rbi*V*(Rbi*Vbi*w - Rbi*w*(V - I*Re)))/((exp(Vbi - V) + 1)*(exp(V - Vo) + 1)*((Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V + I*Re)^2)) - (2*Rbi*V*(Rbi*Vbi*w - Rbi*w*(V - I*Re))*(Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2)/((exp(Vbi - V) + 1)*(exp(V - Vo) + 1)*((Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V + I*Re)^2)^2) + (Rbi*Rp*Rs*V*(Vbi*w - w*(V - I*Re))*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^2)/(exp(Vo - V) + 1);



%data(:,i)=[1/(exp(V - Vbi) + 1) - (I*Rbi^2*Rp^2*Rs + I*Rbi*Rp^2*Rs^2 + I*Rbi*Rs)/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^2) + (2*(I*Rbi*Rp + I*Rbi*Rs + I*Rp*Rs)*(Rbi*Rs*(V - I*Re) - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo + Rbi*Rp^2*Rs^2*(V - I*Re) + Rbi^2*Rp^2*Rs*(V - I*Re)))/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^3) - (I*Rbi*V)/((exp(Vbi - V) + 1)*(exp(V - Vo) + 1)*((Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V + I*Re)^2)) + (Rbi*V*(2*I*(Vbi - V + I*Re) - 2*(Cd*I*Rbi*w + Cg*I*Rbi*w)*(Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w))*(Vbi - V + I*Re))/((exp(Vbi - V) + 1)*(exp(V - Vo) + 1)*((Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V + I*Re)^2)^2)
   % (2*(Rbi*Vo + Rs*Vbi - Rbi*(V - I*Re) - Rs*(V - I*Re))*(Rbi*Rs*(V - I*Re) - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo + Rbi*Rp^2*Rs^2*(V - I*Re) + Rbi^2*Rp^2*Rs*(V - I*Re)))/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^3) - (2*Rbi*Rp*Rs^2*Vbi + 2*Rbi^2*Rp*Rs*Vo - 2*Rbi*Rp*Rs^2*(V - I*Re) - 2*Rbi^2*Rp*Rs*(V - I*Re))/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^2)
   % (Rbi*(V - I*Re) - Rbi^2*Rp^2*Vo + Rbi^2*Rp^2*(V - I*Re) - 2*Rbi*Rp^2*Rs*Vbi + 2*Rbi*Rp^2*Rs*(V - I*Re))/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^2) - (2*(Rbi*(V - I*Re) - Rp*Vbi + Rp*(V - I*Re))*(Rbi*Rs*(V - I*Re) - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo + Rbi*Rp^2*Rs^2*(V - I*Re) + Rbi^2*Rp^2*Rs*(V - I*Re)))/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^3)
    %(Rs*(V - I*Re) - Rp^2*Rs^2*Vbi + Rp^2*Rs^2*(V - I*Re) - 2*Rbi*Rp^2*Rs*Vo + 2*Rbi*Rp^2*Rs*(V - I*Re))/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^2) - (2*(Rp*(V - I*Re) - Rp*Vo + Rs*(V - I*Re))*(Rbi*Rs*(V - I*Re) - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo + Rbi*Rp^2*Rs^2*(V - I*Re) + Rbi^2*Rp^2*Rs*(V - I*Re)))/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^3) - (V*(Vbi - V + I*Re))/((exp(Vbi - V) + 1)*(exp(V - Vo) + 1)*((Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V + I*Re)^2)) + (2*Rbi*V*(Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)*(Cd*w*(V - I*Re) - Cd*Vbi*w + Cg*w*(V - I*Re))*(Vbi - V + I*Re))/((exp(Vbi - V) + 1)*(exp(V - Vo) + 1)*((Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V + I*Re)^2)^2)
   % (Re*exp(V - Vbi))/(exp(V - Vbi) + 1)^2 - (Rbi*Rp^2*Rs^2)/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^2) - (Rbi*V)/((exp(Vbi - V) + 1)*(exp(V - Vo) + 1)*((Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V + I*Re)^2)) + (2*Rp*Rs*(Rbi*Rs*(V - I*Re) - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo + Rbi*Rp^2*Rs^2*(V - I*Re) + Rbi^2*Rp^2*Rs*(V - I*Re)))/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^3) - (Rbi*V*(Vbi - V + I*Re)*(2*V - 2*Vbi - 2*I*Re + 2*Cd*Rbi*w*(Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)))/((exp(Vbi - V) + 1)*(exp(V - Vo) + 1)*((Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V + I*Re)^2)^2) + (Rbi*V*exp(Vbi - V)*(Vbi - V + I*Re))/((exp(Vbi - V) + 1)^2*(exp(V - Vo) + 1)*((Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V + I*Re)^2))
   % (2*Rbi*Rp*(Rbi*Rs*(V - I*Re) - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo + Rbi*Rp^2*Rs^2*(V - I*Re) + Rbi^2*Rp^2*Rs*(V - I*Re)))/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^3) - (Rbi^2*Rp^2*Rs)/((exp(Vo - V) + 1)*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^2) - (exp(Vo - V)*(Rbi*Rs*(V - I*Re) - Rbi*Rp^2*Rs^2*Vbi - Rbi^2*Rp^2*Rs*Vo + Rbi*Rp^2*Rs^2*(V - I*Re) + Rbi^2*Rp^2*Rs*(V - I*Re)))/((exp(Vo - V) + 1)^2*(Rbi*Rp*(V - I*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V - I*Re) + Rp*Rs*(V - I*Re))^2) - (Rbi*V*exp(V - Vo)*(Vbi - V + I*Re))/((exp(Vbi - V) + 1)*(exp(V - Vo) + 1)^2*((Cd*Rbi*w*(V - I*Re) + Cg*Rbi*w*(V - I*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V + I*Re)^2))];
%end