syms Re Rbi Rs Rp Cd Cg V1 Vo Vbi w V I a b c d e V_set(i) I_set(i);
a=1/(1+exp(-Vbi+V_set));
b=1/(1+exp(Vbi-V_set));
c=1/(1+exp(V_set-Vo));
d=b*c;
e=1/(1+exp(Vo-V_set));
V1=V_set-I_set*Re;

f=Re*a+d*(Rbi*V_set(i)*(V1-Vbi))/((V1-Vbi)^2+(V1*w*Cd*Rbi-Vbi*w*Cd*Rbi+V1*Rbi*w*Cg)^2)+e*V_set(i)*(Rbi*Rs*Rp*Rs*Rp*V1-Rbi*Rs*Rp*Rs*Rp*Vbi+Rbi*Rs*Rp*Rbi*Rp*V1-Rbi*Rs*Rp*Rbi*Rp*Vo+Rbi*Rs*Rp*V1*Rbi*Rs)/((V1*Rs*Rp-Vbi*Rs*Rp+V1*Rbi*Rp-Vo*Rbi*Rp+V1*Rbi*Rs)^2+Rbi*Rbi*Rs*Rs*Rp*Rp*(V1*w*Cd-Vbi*w*Cd+V1*w*Cg)^2);

%Re
1/(exp(V_set(i) - Vbi) + 1) - (V_set(i)*(I_set(i)*Rbi^2*Rp^2*Rs + I_set(i)*Rbi^2*Rp*Rs^2 + I_set(i)*Rbi*Rp^2*Rs^2))/(((Rbi*Rp*(V_set(i) - I_set(i)*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set(i) - I_set(i)*Re) + Rp*Rs*(V_set(i) - I_set(i)*Re))^2 + Rbi^2*Rp^2*Rs^2*(Cd*w*(V_set(i) - I_set(i)*Re) - Cd*Vbi*w + Cg*w*(V_set(i) - I_set(i)*Re))^2)*(exp(Vo - V_set(i)) + 1)) + (V_set(i)*(2*(I_set(i)*Rbi*Rp + I_set(i)*Rbi*Rs + I_set(i)*Rp*Rs)*(Rbi*Rp*(V_set(i) - I_set(i)*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set(i) - I_set(i)*Re) + Rp*Rs*(V_set(i) - I_set(i)*Re)) + 2*Rbi^2*Rp^2*Rs^2*(Cd*I_set(i)*w + Cg*I_set(i)*w)*(Cd*w*(V_set(i) - I_set(i)*Re) - Cd*Vbi*w + Cg*w*(V_set(i) - I_set(i)*Re)))*(Rbi*Rp^2*Rs^2*(V_set(i) - I_set(i)*Re) - Rbi^2*Rp^2*Rs*Vo - Rbi*Rp^2*Rs^2*Vbi + Rbi^2*Rp*Rs^2*(V_set(i) - I_set(i)*Re) + Rbi^2*Rp^2*Rs*(V_set(i) - I_set(i)*Re)))/(((Rbi*Rp*(V_set(i) - I_set(i)*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set(i) - I_set(i)*Re) + Rp*Rs*(V_set(i) - I_set(i)*Re))^2 + Rbi^2*Rp^2*Rs^2*(Cd*w*(V_set(i) - I_set(i)*Re) - Cd*Vbi*w + Cg*w*(V_set(i) - I_set(i)*Re))^2)^2*(exp(Vo - V_set(i)) + 1)) - (I_set(i)*Rbi*V_set(i))/((exp(Vbi - V_set(i)) + 1)*(exp(V_set(i) - Vo) + 1)*((Cd*Rbi*w*(V_set(i) - I_set(i)*Re) + Cg*Rbi*w*(V_set(i) - I_set(i)*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V_set(i) + I_set(i)*Re)^2)) + (Rbi*V_set(i)*(2*I_set(i)*(Vbi - V_set(i) + I_set(i)*Re) - 2*(Cd*I_set(i)*Rbi*w + Cg*I_set(i)*Rbi*w)*(Cd*Rbi*w*(V_set(i) - I_set(i)*Re) + Cg*Rbi*w*(V_set(i) - I_set(i)*Re) - Cd*Rbi*Vbi*w))*(Vbi - V_set(i) + I_set(i)*Re))/((exp(Vbi - V_set(i)) + 1)*(exp(V_set(i) - Vo) + 1)*((Cd*Rbi*w*(V_set(i) - I_set(i)*Re) + Cg*Rbi*w*(V_set(i) - I_set(i)*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V_set(i) + I_set(i)*Re)^2)^2)

%Rbi
(V_set(i)*(Rp^2*Rs^2*(V_set(i) - I_set(i)*Re) - Rp^2*Rs^2*Vbi - 2*Rbi*Rp^2*Rs*Vo + 2*Rbi*Rp*Rs^2*(V_set(i) - I_set(i)*Re) + 2*Rbi*Rp^2*Rs*(V_set(i) - I_set(i)*Re)))/(((Rbi*Rp*(V_set(i) - I_set(i)*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set(i) - I_set(i)*Re) + Rp*Rs*(V_set(i) - I_set(i)*Re))^2 + Rbi^2*Rp^2*Rs^2*(Cd*w*(V_set(i) - I_set(i)*Re) - Cd*Vbi*w + Cg*w*(V_set(i) - I_set(i)*Re))^2)*(exp(Vo - V_set(i)) + 1)) - (V_set(i)*(2*(Rp*(V_set(i) - I_set(i)*Re) - Rp*Vo + Rs*(V_set(i) - I_set(i)*Re))*(Rbi*Rp*(V_set(i) - I_set(i)*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set(i) - I_set(i)*Re) + Rp*Rs*(V_set(i) - I_set(i)*Re)) + 2*Rbi*Rp^2*Rs^2*(Cd*w*(V_set(i) - I_set(i)*Re) - Cd*Vbi*w + Cg*w*(V_set(i) - I_set(i)*Re))^2)*(Rbi*Rp^2*Rs^2*(V_set(i) - I_set(i)*Re) - Rbi^2*Rp^2*Rs*Vo - Rbi*Rp^2*Rs^2*Vbi + Rbi^2*Rp*Rs^2*(V_set(i) - I_set(i)*Re) + Rbi^2*Rp^2*Rs*(V_set(i) - I_set(i)*Re)))/(((Rbi*Rp*(V_set(i) - I_set(i)*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set(i) - I_set(i)*Re) + Rp*Rs*(V_set(i) - I_set(i)*Re))^2 + Rbi^2*Rp^2*Rs^2*(Cd*w*(V_set(i) - I_set(i)*Re) - Cd*Vbi*w + Cg*w*(V_set(i) - I_set(i)*Re))^2)^2*(exp(Vo - V_set(i)) + 1)) - (V_set(i)*(Vbi - V_set(i) + I_set(i)*Re))/((exp(Vbi - V_set(i)) + 1)*(exp(V_set(i) - Vo) + 1)*((Cd*Rbi*w*(V_set(i) - I_set(i)*Re) + Cg*Rbi*w*(V_set(i) - I_set(i)*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V_set(i) + I_set(i)*Re)^2)) + (2*Rbi*V_set(i)*(Cd*Rbi*w*(V_set(i) - I_set(i)*Re) + Cg*Rbi*w*(V_set(i) - I_set(i)*Re) - Cd*Rbi*Vbi*w)*(Cd*w*(V_set(i) - I_set(i)*Re) - Cd*Vbi*w + Cg*w*(V_set(i) - I_set(i)*Re))*(Vbi - V_set(i) + I_set(i)*Re))/((exp(Vbi - V_set(i)) + 1)*(exp(V_set(i) - Vo) + 1)*((Cd*Rbi*w*(V_set(i) - I_set(i)*Re) + Cg*Rbi*w*(V_set(i) - I_set(i)*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V_set(i) + I_set(i)*Re)^2)^2)

%Rs
(V_set(i)*(Rbi^2*Rp^2*(V_set(i) - I_set(i)*Re) - Rbi^2*Rp^2*Vo - 2*Rbi*Rp^2*Rs*Vbi + 2*Rbi*Rp^2*Rs*(V_set(i) - I_set(i)*Re) + 2*Rbi^2*Rp*Rs*(V_set(i) - I_set(i)*Re)))/(((Rbi*Rp*(V_set(i) - I_set(i)*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set(i) - I_set(i)*Re) + Rp*Rs*(V_set(i) - I_set(i)*Re))^2 + Rbi^2*Rp^2*Rs^2*(Cd*w*(V_set(i) - I_set(i)*Re) - Cd*Vbi*w + Cg*w*(V_set(i) - I_set(i)*Re))^2)*(exp(Vo - V_set(i)) + 1)) - (V_set(i)*(2*(Rbi*(V_set(i) - I_set(i)*Re) - Rp*Vbi + Rp*(V_set(i) - I_set(i)*Re))*(Rbi*Rp*(V_set(i) - I_set(i)*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set(i) - I_set(i)*Re) + Rp*Rs*(V_set(i) - I_set(i)*Re)) + 2*Rbi^2*Rp^2*Rs*(Cd*w*(V_set(i) - I_set(i)*Re) - Cd*Vbi*w + Cg*w*(V_set(i) - I_set(i)*Re))^2)*(Rbi*Rp^2*Rs^2*(V_set(i) - I_set(i)*Re) - Rbi^2*Rp^2*Rs*Vo - Rbi*Rp^2*Rs^2*Vbi + Rbi^2*Rp*Rs^2*(V_set(i) - I_set(i)*Re) + Rbi^2*Rp^2*Rs*(V_set(i) - I_set(i)*Re)))/(((Rbi*Rp*(V_set(i) - I_set(i)*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set(i) - I_set(i)*Re) + Rp*Rs*(V_set(i) - I_set(i)*Re))^2 + Rbi^2*Rp^2*Rs^2*(Cd*w*(V_set(i) - I_set(i)*Re) - Cd*Vbi*w + Cg*w*(V_set(i) - I_set(i)*Re))^2)^2*(exp(Vo - V_set(i)) + 1))


%Rp
(V_set(i)*(Rbi^2*Rs^2*(V_set(i) - I_set(i)*Re) - 2*Rbi*Rp*Rs^2*Vbi - 2*Rbi^2*Rp*Rs*Vo + 2*Rbi*Rp*Rs^2*(V_set(i) - I_set(i)*Re) + 2*Rbi^2*Rp*Rs*(V_set(i) - I_set(i)*Re)))/(((Rbi*Rp*(V_set(i) - I_set(i)*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set(i) - I_set(i)*Re) + Rp*Rs*(V_set(i) - I_set(i)*Re))^2 + Rbi^2*Rp^2*Rs^2*(Cd*w*(V_set(i) - I_set(i)*Re) - Cd*Vbi*w + Cg*w*(V_set(i) - I_set(i)*Re))^2)*(exp(Vo - V_set(i)) + 1)) + (V_set(i)*(2*(Rbi*Vo + Rs*Vbi - Rbi*(V_set(i) - I_set(i)*Re) - Rs*(V_set(i) - I_set(i)*Re))*(Rbi*Rp*(V_set(i) - I_set(i)*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set(i) - I_set(i)*Re) + Rp*Rs*(V_set(i) - I_set(i)*Re)) - 2*Rbi^2*Rp*Rs^2*(Cd*w*(V_set(i) - I_set(i)*Re) - Cd*Vbi*w + Cg*w*(V_set(i) - I_set(i)*Re))^2)*(Rbi*Rp^2*Rs^2*(V_set(i) - I_set(i)*Re) - Rbi^2*Rp^2*Rs*Vo - Rbi*Rp^2*Rs^2*Vbi + Rbi^2*Rp*Rs^2*(V_set(i) - I_set(i)*Re) + Rbi^2*Rp^2*Rs*(V_set(i) - I_set(i)*Re)))/(((Rbi*Rp*(V_set(i) - I_set(i)*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set(i) - I_set(i)*Re) + Rp*Rs*(V_set(i) - I_set(i)*Re))^2 + Rbi^2*Rp^2*Rs^2*(Cd*w*(V_set(i) - I_set(i)*Re) - Cd*Vbi*w + Cg*w*(V_set(i) - I_set(i)*Re))^2)^2*(exp(Vo - V_set(i)) + 1))



%Vo
(2*Rbi*Rp*V_set(i)*(Rbi*Rp*(V_set(i) - I_set(i)*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set(i) - I_set(i)*Re) + Rp*Rs*(V_set(i) - I_set(i)*Re))*(Rbi*Rp^2*Rs^2*(V_set(i) - I_set(i)*Re) - Rbi^2*Rp^2*Rs*Vo - Rbi*Rp^2*Rs^2*Vbi + Rbi^2*Rp*Rs^2*(V_set(i) - I_set(i)*Re) + Rbi^2*Rp^2*Rs*(V_set(i) - I_set(i)*Re)))/(((Rbi*Rp*(V_set(i) - I_set(i)*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set(i) - I_set(i)*Re) + Rp*Rs*(V_set(i) - I_set(i)*Re))^2 + Rbi^2*Rp^2*Rs^2*(Cd*w*(V_set(i) - I_set(i)*Re) - Cd*Vbi*w + Cg*w*(V_set(i) - I_set(i)*Re))^2)^2*(exp(Vo - V_set(i)) + 1)) - (Rbi^2*Rp^2*Rs*V_set(i))/(((Rbi*Rp*(V_set(i) - I_set(i)*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set(i) - I_set(i)*Re) + Rp*Rs*(V_set(i) - I_set(i)*Re))^2 + Rbi^2*Rp^2*Rs^2*(Cd*w*(V_set(i) - I_set(i)*Re) - Cd*Vbi*w + Cg*w*(V_set(i) - I_set(i)*Re))^2)*(exp(Vo - V_set(i)) + 1)) - (V_set(i)*exp(Vo - V_set(i))*(Rbi*Rp^2*Rs^2*(V_set(i) - I_set(i)*Re) - Rbi^2*Rp^2*Rs*Vo - Rbi*Rp^2*Rs^2*Vbi + Rbi^2*Rp*Rs^2*(V_set(i) - I_set(i)*Re) + Rbi^2*Rp^2*Rs*(V_set(i) - I_set(i)*Re)))/(((Rbi*Rp*(V_set(i) - I_set(i)*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set(i) - I_set(i)*Re) + Rp*Rs*(V_set(i) - I_set(i)*Re))^2 + Rbi^2*Rp^2*Rs^2*(Cd*w*(V_set(i) - I_set(i)*Re) - Cd*Vbi*w + Cg*w*(V_set(i) - I_set(i)*Re))^2)*(exp(Vo - V_set(i)) + 1)^2) - (Rbi*V_set(i)*exp(V_set(i) - Vo)*(Vbi - V_set(i) + I_set(i)*Re))/((exp(Vbi - V_set(i)) + 1)*(exp(V_set(i) - Vo) + 1)^2*((Cd*Rbi*w*(V_set(i) - I_set(i)*Re) + Cg*Rbi*w*(V_set(i) - I_set(i)*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V_set(i) + I_set(i)*Re)^2))


%Vbi
(Re*exp(V_set(i) - Vbi))/(exp(V_set(i) - Vbi) + 1)^2 - (Rbi*V_set(i))/((exp(Vbi - V_set(i)) + 1)*(exp(V_set(i) - Vo) + 1)*((Cd*Rbi*w*(V_set(i) - I_set(i)*Re) + Cg*Rbi*w*(V_set(i) - I_set(i)*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V_set(i) + I_set(i)*Re)^2)) + (V_set(i)*(2*Rp*Rs*(Rbi*Rp*(V_set(i) - I_set(i)*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set(i) - I_set(i)*Re) + Rp*Rs*(V_set(i) - I_set(i)*Re)) + 2*Cd*Rbi^2*Rp^2*Rs^2*w*(Cd*w*(V_set(i) - I_set(i)*Re) - Cd*Vbi*w + Cg*w*(V_set(i) - I_set(i)*Re)))*(Rbi*Rp^2*Rs^2*(V_set(i) - I_set(i)*Re) - Rbi^2*Rp^2*Rs*Vo - Rbi*Rp^2*Rs^2*Vbi + Rbi^2*Rp*Rs^2*(V_set(i) - I_set(i)*Re) + Rbi^2*Rp^2*Rs*(V_set(i) - I_set(i)*Re)))/(((Rbi*Rp*(V_set(i) - I_set(i)*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set(i) - I_set(i)*Re) + Rp*Rs*(V_set(i) - I_set(i)*Re))^2 + Rbi^2*Rp^2*Rs^2*(Cd*w*(V_set(i) - I_set(i)*Re) - Cd*Vbi*w + Cg*w*(V_set(i) - I_set(i)*Re))^2)^2*(exp(Vo - V_set(i)) + 1)) - (Rbi*Rp^2*Rs^2*V_set(i))/(((Rbi*Rp*(V_set(i) - I_set(i)*Re) - Rp*Rs*Vbi - Rbi*Rp*Vo + Rbi*Rs*(V_set(i) - I_set(i)*Re) + Rp*Rs*(V_set(i) - I_set(i)*Re))^2 + Rbi^2*Rp^2*Rs^2*(Cd*w*(V_set(i) - I_set(i)*Re) - Cd*Vbi*w + Cg*w*(V_set(i) - I_set(i)*Re))^2)*(exp(Vo - V_set(i)) + 1)) - (Rbi*V_set(i)*(Vbi - V_set(i) + I_set(i)*Re)*(2*V_set(i) - 2*Vbi - 2*I_set(i)*Re + 2*Cd*Rbi*w*(Cd*Rbi*w*(V_set(i) - I_set(i)*Re) + Cg*Rbi*w*(V_set(i) - I_set(i)*Re) - Cd*Rbi*Vbi*w)))/((exp(Vbi - V_set(i)) + 1)*(exp(V_set(i) - Vo) + 1)*((Cd*Rbi*w*(V_set(i) - I_set(i)*Re) + Cg*Rbi*w*(V_set(i) - I_set(i)*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V_set(i) + I_set(i)*Re)^2)^2) + (Rbi*V_set(i)*exp(Vbi - V_set(i))*(Vbi - V_set(i) + I_set(i)*Re))/((exp(Vbi - V_set(i)) + 1)^2*(exp(V_set(i) - Vo) + 1)*((Cd*Rbi*w*(V_set(i) - I_set(i)*Re) + Cg*Rbi*w*(V_set(i) - I_set(i)*Re) - Cd*Rbi*Vbi*w)^2 + (Vbi - V_set(i) + I_set(i)*Re)^2))



%


%