function data = Jacob_matrix_im_v(V_set, I_set, paramater_set)

% the six paramaters are Re, Rp, Rs, Rbi, Vbi, Vo
paramater_type_num = 9;
Re= paramater_set(1,1);
Rp= paramater_set(2,1);
Rs= paramater_set(3,1);
Rbi= paramater_set(4,1);
Vbi= paramater_set(5,1);
Vo=paramater_set(6,1);
slope_factor_for_vbi = paramater_set(7,1);
slope_factor_for_vo1 = paramater_set(8,1);
slope_factor_for_vo2 = paramater_set(9,1);
% Jacobian matrix
% 这里的Jacobian矩阵是指的是对于每一个参数，对于每一个参数的导数
data = zeros(paramater_type_num ,paramater_type_num);

% to be implemented
for i = 1:paramater_type_num
data(i,:)=[
((Vbi - V_set(i))/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + (Vo - V_set(i))/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) - V_set(i)/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)))/(Re^3*(1/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + 1/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)) + 1/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) + 1/Re)^2) - ((Vbi - V_set(i))/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + (Vo - V_set(i))/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) - V_set(i)/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)))/(Re^2*(1/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + 1/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)) + 1/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) + 1/Re))
((Vbi - V_set(i))/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + (Vo - V_set(i))/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) - V_set(i)/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)))/(Re*Rp^2*I_set(i)*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)*(1/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + 1/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)) + 1/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) + 1/Re)^2) + V_set(i)/(Re*Rp^2*I_set(i)*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)*(1/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + 1/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)) + 1/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) + 1/Re))
((Vbi - V_set(i))/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + (Vo - V_set(i))/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) - V_set(i)/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)))/(Re*Rs^2*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)*(1/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + 1/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)) + 1/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) + 1/Re)^2) - (Vo - V_set(i))/(Re*Rs^2*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)*(1/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + 1/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)) + 1/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) + 1/Re))
((Vbi - V_set(i))/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + (Vo - V_set(i))/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) - V_set(i)/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)))/(Rbi^2*Re*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)*(1/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + 1/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)) + 1/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) + 1/Re)^2) - (Vbi - V_set(i))/(Rbi^2*Re*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)*(1/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + 1/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)) + 1/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) + 1/Re))
(1/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) - (exp((Vbi - V_set(i))/slope_factor_for_vbi)*(Vbi - V_set(i)))/(Rbi*slope_factor_for_vbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)^2))/(Re*(1/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + 1/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)) + 1/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) + 1/Re)) + (exp((Vbi - V_set(i))/slope_factor_for_vbi)*((Vbi - V_set(i))/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + (Vo - V_set(i))/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) - V_set(i)/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1))))/(Rbi*Re*slope_factor_for_vbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)^2*(1/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + 1/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)) + 1/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) + 1/Re)^2)
(1/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) + (exp((Vo - V_set(i))/slope_factor_for_vo1)*V_set(i))/(Rp*slope_factor_for_vo1*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)^2) - (exp((Vo - V_set(i))/slope_factor_for_vo2)*(Vo - V_set(i)))/(Rs*slope_factor_for_vo2*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)^2))/(Re*(1/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + 1/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)) + 1/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) + 1/Re)) + ((exp((Vo - V_set(i))/slope_factor_for_vo1)/(Rp*slope_factor_for_vo1*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)^2) + exp((Vo - V_set(i))/slope_factor_for_vo2)/(Rs*slope_factor_for_vo2*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)^2))*((Vbi - V_set(i))/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + (Vo - V_set(i))/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) - V_set(i)/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1))))/(Re*(1/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + 1/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)) + 1/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) + 1/Re)^2)
(exp((Vbi - V_set(i))/slope_factor_for_vbi)*(Vbi - V_set(i))^2)/(Rbi*Re*slope_factor_for_vbi^2*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)^2*(1/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + 1/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)) + 1/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) + 1/Re)) - (exp((Vbi - V_set(i))/slope_factor_for_vbi)*(Vbi - V_set(i))*((Vbi - V_set(i))/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + (Vo - V_set(i))/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) - V_set(i)/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1))))/(Rbi*Re*slope_factor_for_vbi^2*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)^2*(1/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + 1/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)) + 1/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) + 1/Re)^2)
- (exp((Vo - V_set(i))/slope_factor_for_vo1)*(Vo - V_set(i))*((Vbi - V_set(i))/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + (Vo - V_set(i))/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) - V_set(i)/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1))))/(Re*Rp*slope_factor_for_vo1^2*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)^2*(1/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + 1/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)) + 1/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) + 1/Re)^2) - (exp((Vo - V_set(i))/slope_factor_for_vo1)*V_set(i)*(Vo - V_set(i)))/(Re*Rp*slope_factor_for_vo1^2*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)^2*(1/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + 1/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)) + 1/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) + 1/Re))
(exp((Vo - V_set(i))/slope_factor_for_vo2)*(Vo - V_set(i))^2)/(Re*Rs*slope_factor_for_vo2^2*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)^2*(1/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + 1/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)) + 1/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) + 1/Re)) - (exp((Vo - V_set(i))/slope_factor_for_vo2)*(Vo - V_set(i))*((Vbi - V_set(i))/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + (Vo - V_set(i))/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) - V_set(i)/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1))))/(Re*Rs*slope_factor_for_vo2^2*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)^2*(1/(Rbi*(exp((Vbi - V_set(i))/slope_factor_for_vbi) + 1)) + 1/(Rp*(exp((Vo - V_set(i))/slope_factor_for_vo1) + 1)) + 1/(Rs*(exp((Vo - V_set(i))/slope_factor_for_vo2) + 1)) + 1/Re)^2)
];
end